service: domychores

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"

functions:
  register:
    handler: api/auth.register
    memorySize: 128
    description: Submit user's credentials in DynamoDB.
    events:
      - http: 
          path: /api/register
          method: post
          cors: true
  login:
    handler: api/auth.login
    memorySize: 128
    description: Verify user's credentials from DynamoDB.
    events:
      - http:
          path: /api/login
          method: post
          cors: true

  transaction-getAllRequests:
    handler: api/transaction.getAllRequest
    memorySize: 128
    description: Get all the transactions.
    events:
      - http:
          path: /api/service-requests/
          method: get
          cors: true

  transaction-getRequestPerUser:
    handler: api/transaction.getRequestPerUser
    memorySize: 128
    description: Get all the transaction associated with the requester or tasker.
    events:
      - http:
          path: /api/service-requests/get-user
          method: get
          cors: true

  transaction-create:
    handler: api/transaction.createRequest
    memorySize: 128
    description: Create a new transaction and associate with a requester.
    events:
      - http:
          path: /api/service-requests/create
          method: post
          cors: true

  transaction-delete:
    handler: api/transaction.deleteRequest
    memorySize: 128
    description: Remove a transaction.
    events:
      - http:
          path: /api/service-requests/delete/{id}
          method: delete
          cors: true

  transaction-getStatus:
    handler: api/transaction.getStatus
    memorySize: 128
    description: Get status of a transaction.
    events:
      - http:
          path: /api/service-requests/get-status/{id}
          method: get
          cors: true

  transaction-taskerAccept:
    handler: api/transaction.taskerAccept
    memorySize: 128
    description: Update transaction when tasker accepts a service request.
    events:
      - http:
          path: /api/service-requests/tasker-accept
          method: post
          cors: true

  transaction-taskerSetCompleteTask:
    handler: api/transaction.taskerSetCompleteTask
    memorySize: 128
    description: Update transaction when tasker completes a service request.
    events:
      - http:
          path: /api/service-requests/tasker-complete
          method: post
          cors: true

  profile-getProfileByUsername:
    handler: api/profile.getProfileUsername
    memorySize: 128
    description: Retrieve profile information using username.
    events:
      - http:
          path: /api/profile/{username}
          method: get
          cors: true

  review-getReview:
    handler: api/review.getReviewsUsingUsername
    memorySize: 128
    description: Get a review using username.
    events:
      - http:
          path: /api/review/{username}
          method: get
          cors: true

  review-addReview:
    handler: api/review.addReview
    memorySize: 128
    description: Add a review.
    events:
      - http:
          path: /api/review/add
          method: post
          cors: true

  review-deleteReview:
    handler: api/review.deleteReview
    memorySize: 128
    description: Delete a review using review ID.
    events:
      - http:
          path: /api/review/delete/{id}
          method: delete
          cors: true