service: domychores

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"

functions:
  register:
    handler: api/auth.register
    memorySize: 128
    description: Submit user's credentials in DynamoDB.
    events:
      - http: 
          path: /api/register
          method: post
          cors: true
  login:
    handler: api/auth.login
    memorySize: 128
    description: Verify user's credentials from DynamoDB.
    events:
      - http:
          path: /api/login
          method: post
          cors: true